# Generated by Django 3.1 on 2024-07-18 21:07

from django.db import migrations, models
import django.db.models.deletion



class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='numero_serie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edicion', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='tienda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_fabricacion', models.DateField()),
                ('descripcion', models.CharField(max_length=500)),
                ('precio', models.IntegerField()),
                ('unidades', models.IntegerField()),
                ('nuevo', models.BooleanField()),
                ('numero_serie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.numero_serie')),
            ],
        ),
    ]
