# Generated by Django 3.1 on 2024-07-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_contacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.IntegerField()),
                ('nombreusuario', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('constraseña', models.CharField(max_length=10)),
            ],
        ),
    ]
